version: "2"

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/www/app/volumes/web/conf.d:/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./volumes/proxy/certs:/etc/nginx/certs:ro"
    logging:
      options:
        max-size: 20m
  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./volumes/proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    logging:
      options:
        max-size: 10m
  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/proxy/certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    logging:
      options:
        max-size: 10m
  web:
    restart: always
    image: WEB_IMAGE
    container_name: web
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - VIRTUAL_HOST=DOMAIN.com,www.DOMAIN.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=DOMAIN.com,www.DOMAIN.com
      - LETSENCRYPT_EMAIL=jerryc.nguyen91@gmail.com
    command: "bundle exec puma -C config/puma.rb config.ru && bundle exec rake log:clear"
    logging:
      options:
        max-size: 20m
