version: '2'

services:
  nginx-proxy:
    image: nginx:1.26-alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # The vhost volume is only required if you
      # plan to obtain standalone certificates
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - ./deploy/http.conf:/etc/nginx/conf.d/http.conf

  docker-gen:
    image: nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./deploy/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    labels:
      - 'com.github.nginx-proxy.docker-gen'

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=jerryc.nguyen91@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

  web:
    restart: always
    image: registry.gitlab.com/jerryc.nguyen91/docker:production
    container_name: web
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=DOMAIN.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=DOMAIN.com
      - LETSENCRYPT_EMAIL=jerryc.nguyen91@gmail.com
    command: 'bundle exec puma -C config/puma.rb config.ru && bundle exec rake log:clear'
